Parallels/vagrant-parallels

lib/vagrant-parallels/cap/nic_mac_addresses.rb, lib/vagrant-parallels/driver/base.rb, lib/vagrant-parallels/driver/pd_8.rb, lib/vagrant-parallels/errors.rb, locales/en.yml, test/unit/support/shared/parallels_context.rb, test/unit/support/shared/pd_driver_examples.rb
This PR is going to help some folks to do tricky re-ordering of network interfaces: GH-185
In these cases "Shared" network adapter can have some other index, different from `net0`. So, we have to look at all network interfaces while doing the MAC address search.
If there is no "Shared" adapter found, then an error message will be displayed. It prevents ineffective "Waiting for the machine to boot", like GH-187
cc:\ @racktear @Gray-Wind
=> Use MAC address of the first found Shared adapter

lib/vagrant-parallels/driver/base.rb
Array#each returns the [array] object it was invoked upon, so in case `util_path` doesn't find the executable, it would return the array `['/usr/local/bin', '/usr/bin']`, despite the rest of the code relies on it returning nil in case of failure.
=> Let `util_path` return nil on failure

lib/vagrant-parallels/action/import.rb, lib/vagrant-parallels/config.rb, lib/vagrant-parallels/driver/base.rb, lib/vagrant-parallels/driver/meta.rb, lib/vagrant-parallels/driver/pd_11.rb, lib/vagrant-parallels/errors.rb, lib/vagrant-parallels/plugin.rb, locales/en.yml, test/acceptance/provider/linked_clone_spec.rb, test/acceptance/skeletons/linked_clone/Vagrantfile
*NB! This feature will be available officially only after Parallels Desktop 11 release*
It is called "Create VM as a linked clone", e.q. on the first `vagrant up` the virtual machine will be created as a linked clone of the box image. 
- Regular clone is a full image copy, which is independent from the box. The linked clone is bounded to the specific snapshot of the box image. It means that box deletion will cause all its linked clones being corrupted!
- Linked clone creation is extremely faster than the regular cloning, because there is no image copying process.
- Linked clones require much less disk space, because initially hard disk image size is less than 1Mb (it is bounded to the parent's snapshot)
This feature is disabled by default, e.q. the VM creation is performed through the …
=> Feature pre-release: Linked clones support for Parallels Desktop 11

lib/vagrant-parallels/driver/base.rb, test/unit/driver/pd_8_test.rb, test/unit/driver/pd_9_test.rb, test/unit/support/shared/pd_driver_examples.rb
Fixes [GH-194]
In some cases there are multiple DHCP leases for one network interface, so we should use the most recent lease.
=> Use most recent DHCP lease when determining an IP

lib/vagrant-parallels/driver/base.rb
Fixes GH-204
This is a workaround for the case when `prlsrvctl --json` contains messy symbols.
We should try to fetch JSON string using the regexp and try to parse it again.
cc: @racktear @Gray-Wind
=> driver: Retry to parse json

lib/vagrant-parallels/action/destroy.rb, lib/vagrant-parallels/action/import.rb, lib/vagrant-parallels/action/sane_defaults.rb, lib/vagrant-parallels/driver/base.rb, lib/vagrant-parallels/driver/pd_10.rb
Fixes #178
Previously, `disable_password_restrictions ` was useless because it was called after the `Import` action.
I've fixed that by moving it directly to `Import` and `Destroy` actions
=> Disable password restrictions before #import and #destroy actions

lib/vagrant-parallels/action.rb, lib/vagrant-parallels/action/sane_defaults.rb, locales/en.yml
Fixes #186, #182, #124, #39 
This PR adds a new behavior to the initial `vagrant up`. There are a bunch of default settings which will be applied to each new virtual machine. 
These settings will be applied only once, right after the VM is cloned (after `Import` action). So that, user will be able to override them manually (via GUI or `prlctl`) or using the `customize` settings in Vagrantfile:
```ruby
config.vm.provider "parallels" do |prl|
prl.customize ["set", :id, "--startup-view", "window"]
prl.customize ["set", :id, "--on-window-close", "suspend"]
#...
end
```
These are options for `prlctl set <vm_uuid> ...` 
1. For Parallels Desktop >= 9:
`--startup-view same`
`--on-shutdown close`
`--on-window-close keep-running`
`--auto-share-camera off`
`--smart-guard off`
`--longer-battery-life …
=> Set default configuration for VM right after Import action

lib/vagrant-parallels/config.rb, locales/en.yml, website/docs/source/docs/configuration.html.md
We decide to manage all VM options with the single approach, using `customize`, like this:
```ruby
config.vm.provider "parallels" do |prl|
prl.customize ["set", :id, "--longer-battery-life", "off"]
end
```
Related to changed introduced by GH-215
=> Deprecate "optimize_power_consumption" setting

lib/vagrant-parallels/synced_folder.rb
This is a actual for Windows guests, where colon is the part of any absolute path.
Parallels Desktop replaces colons (:) by asterisks (*) on the guest side, which breaks the synced folder
mapping for Vagrant.
Fixes GH-220
=> Escape colon in synced folder id

lib/vagrant-parallels/driver/base.rb, lib/vagrant-parallels/driver/meta.rb, lib/vagrant-parallels/errors.rb, locales/en.yml
This PR fixes issue GH-219 (or at least minimizes the chance of occurrence).
Sometimes some non-valid characters could be in the json-formatted output `prlctl` and `prlsrvctl` utilities. It causes a human unfriendly exception like described in GH-219.
This PR changes the following:
1) `json` method doesn't support default return value. It will either return the parsed Ruby data structure, or will raise a human-friendly error.
2) Before raising an error it will try to trim all control characters unsupported by JSON (from `\u0000` to `u001f`).
cc: @racktear @Gray-Wind
=> Retry JSON parsing and display readble error if it is failed

lib/vagrant-parallels/action/forward_ports.rb
While doing a parallel run of multi-machine environment the race condition could happen:
```console
...
There was an error while command execution. The command and stderr is shown below.
Command: ["/usr/local/bin/prlsrvctl", "net", "set", "Shared", "--nat-tcp-add", "winrm,2200,8977eda8-08ae-46d3-8923-469d8091ad69,5985", "--nat-tcp-add", "winrm-ssl,2201,8977eda8-08ae-46d3-8923-469d8091ad69,5986"]
Stderr: The rule with 'winrm' name already exists!
```
This PR fixes that by adding adds both class- and process-level locks, so port forwarding will be proceeded subsequently.
Also, I've improved the `forward_ports ` helper by decreasing the number of driver method calls. Now it should work a little bit faster.
cc: @Gray-Wind @racktear @Kasen
=> Fix port forwarding collisions in parallel run of multi-machine env

Gemfile, lib/vagrant-parallels/action.rb, lib/vagrant-parallels/action/box_register.rb, lib/vagrant-parallels/action/box_unregister.rb, lib/vagrant-parallels/action/export.rb, lib/vagrant-parallels/action/import.rb, lib/vagrant-parallels/action/prepare_clone_snapshot.rb, lib/vagrant-parallels/action/set_name.rb, lib/vagrant-parallels/config.rb, lib/vagrant-parallels/driver/base.rb, lib/vagrant-parallels/driver/meta.rb, lib/vagrant-parallels/driver/pd_11.rb, lib/vagrant-parallels/errors.rb, lib/vagrant-parallels/plugin.rb, locales/en.yml, test/unit/support/shared/pd_driver_examples.rb
There is a pretty big PR mostly related to the `Import` action refactoring and adding the support of "Clone another Vagrant environment" (which is an experimental feature and is not documented)
* `Import` action split: box register/unregister logic is moved to standalone actions `BoxRegister` and `BoxUnregister`
* Linked clone management moved to the standalone action `PrepareCloneSnapshot`
* Add support of core feature "Clone another Vagrant environment" (https://github.com/mitchellh/vagrant/pull/6378). It is hidden, but in few words it allows to create a new Vagrant VM not only from the box-shipped template, but by cloning an existing Vagrant VM as well. 
In case of Parallels provider both of full and linked clones are supported.
* Supported Vagrant version is restricted to 1.8+ , …
=> Support core feature `config.vm.clone`

lib/vagrant-parallels/action/box_register.rb, lib/vagrant-parallels/action/snapshot_delete.rb, lib/vagrant-parallels/action/snapshot_restore.rb, lib/vagrant-parallels/action/snapshot_save.rb, lib/vagrant-parallels/cap/snapshot_list.rb, lib/vagrant-parallels/driver/base.rb, lib/vagrant-parallels/plugin.rb
In Vagrant 1.8 there will be new feature added: https://github.com/mitchellh/vagrant/pull/6374
In few words, it allows to manage VM snapshots with command `vagrant snapshot`
BTW, it was implemented two years ago by ["sahara"](https://github.com/jedi4ever/sahara) plugin ;-)
So, we should definitely support this feature. And thankfully to GH-224, it was not so hard to implement.
@Gray-Wind @Kasen @racktear
=> Support for "Snapshot" feature (Vagrant 1.8+)

lib/vagrant-parallels/driver/meta.rb
Actually, Parallels Desktop version is not changing during the Vagrant run.
So, we can cache it on the class level to speed up the execution and avoid extra `prlctl --version` calls.
This is a port of upstream PR: https://github.com/mitchellh/vagrant/pull/6552
=> driver/meta: cache Parallels Desktop version

lib/vagrant-parallels/action/network.rb, website/docs/source/docs/networking/public_network.html.md
This PR ports the similar one from the upstream: https://github.com/mitchellh/vagrant/pull/5691
This change allows you to specify multiple network interfaces to bridge to in the order you want them tried, picking the first match:
```
config.vm.network "public_network", bridge: ["en1", "en6"]
```
cc: @racktear
=> Networking: handle a list of bridged NICs

website/docs/Gemfile, website/docs/Procfile, website/docs/source/docs/boxes/index.html.md, website/docs/source/docs/boxes/packer.html.md, website/docs/source/docs/boxes/veewee.html.md, website/docs/source/docs/configuration.html.md, website/docs/source/docs/getting-started.html.md, website/docs/source/docs/share.html.md, website/docs/source/docs/usage.html.md
* Removed Procfile and unused gems from Gemfile
* Change example box name to "ubuntu-14.04"
* Add "brew" way for installing Parallels Virtualization SDK
* Update "boxes" index page
* Change name and link "VagrantCloud" to "Atlas"
* Update "linked clone" feature description
* Update URL for "Parallels Tools Overview" and "Command-Line Reference"
cc: @racktear
=> Update documentation site

lib/vagrant-parallels/guest_cap/darwin/install_parallels_tools.rb, lib/vagrant-parallels/plugin.rb, website/docs/source/docs/configuration.html.md
:tada: 
It makes possible to install/update Parallels Tools for Mac
=> Add "install_parallels_tools" guest cap for Darwin guests

lib/vagrant-parallels/action/box_register.rb, lib/vagrant-parallels/action/import.rb, lib/vagrant-parallels/driver/base.rb
Fixes GH-239
In parallel env `prlctl register` is called once for all machines, and SourceVmUuid is not unique.
So, we have to pass this option to `prlctl clone` command instead.
This option is supported for Parallels Desktop >= 10.1.2.
For earlier versions we still have to regenerate SourceVmUuid by editing `config.pvs`
=> Pass "--regenerate-src-uuid" option to the command "clone"

lib/vagrant-parallels/action/box_register.rb, lib/vagrant-parallels/action/box_unregister.rb, lib/vagrant-parallels/driver/base.rb
Fixes GH-243
In parallel run of multi-machine environment the same box image could be cloning
simultaneously by more then one envs. But the box should be unregister exactly by the last env.
To prevent a race condition here, we add a temporary lease file with a counter.
It is incremented for incoming envs (new clones) and decremented right after the cloning.
The last env removes the lock file and unregisters the box.
cc: @racktear @Gray-Wind @Kasen
=> Boxes: Use temporary lock file to prevent early unregister

lib/vagrant-parallels/action.rb, test/acceptance/provider/snapshot_spec.rb
Fixes #253
Completes "Snapshot" feature support introduced by https://github.com/Parallels/vagrant-parallels/pull/228
Now actions are defined, so the following commands should work fine with our provider: 
`vagrant snapshot save|restore|delete|push|pop`
=> Define provider actions for snapshot management

locales/en.yml
I've re-phrased the massage which appears if `prlctl` binary couldn't be found.
We should explain users that our provider requires either Pro or Business edition of Parallels Desktop.
cc: @racktear
=> Fix "parallels_not_detected" error message

lib/vagrant-parallels/action/sane_defaults.rb
Implements GH-171 for Parallels Desktop 11+
Due to request GH-171 there was a new CLI option added in PD 11:
```
prlctl set <vm_uuid> --shf-host-defined <off|alldisks|home>
```
By default all Parallels Desktop VMs has this option set to `"home"`, so that user's home folder (from the Mac host) is accessible for read & write from the guest VMs. In Linux VMs its content could be found at `/media/psf/Home`
I suggest to set this option to `off` for all VMs managed by our Vagrant provider, as we do for other host<=>guest integration features (see GH-215). This is needed for security reasons and helps to isolate dev environment from the Mac host.
cc: @Kasen @racktear
=> Disable home folder sharing by default (Parallels Desktop 11+)

lib/vagrant-parallels/config.rb, test/unit/config_test.rb
Vagrantfile options `regen_box_uuid` and `use_linked_clone` are marked as deprecated in favor of `regen_src_uuid ` and `linked_clone` appropriately.
Old options are still working, but will be removed in `vagrant-parallels` v1.7.0
cc: @racktear
=> config: Add warning message about deprecated options

lib/vagrant-parallels/driver/base.rb
Sometimes `prlctl` could fail on "snapshot-delete'" and "snapshot-switch" commands with an error like this:
> Failed to delete snapshot: The operation cannot be performed at the moment. Data synchronization is currently in progress. Try to perform the operation later.
This issue should be fixed on the Parallels Desktop side. But at the moment, this PR works it around.
cc: @racktear
=> Add retries for snapshot commands

lib/vagrant-parallels/action/box_unregister.rb
There is no box specified in layered env. So, this action recovery should be just skipped.
cc @ar7em
=> action/box_unregister: Fix #recover for layered envs

lib/vagrant-parallels/action/export.rb, lib/vagrant-parallels/driver/base.rb, lib/vagrant-parallels/driver/meta.rb, lib/vagrant-parallels/errors.rb, locales/en.yml, test/acceptance/provider/package_spec.rb, test/unit/support/shared/pd_driver_examples.rb
This PR makes possible to use `vagrant package` for environments created as linked clones.
External disk images will be automatically copied, so the resulted box become a full-sized standalone VM.
cc: @Kasen, @racktear, @Gray-Wind
=> Support for packaging linked clones

lib/vagrant-parallels/action/network.rb, lib/vagrant-parallels/driver/base.rb, lib/vagrant-parallels/driver/pd_10.rb, lib/vagrant-parallels/driver/pd_8.rb
Similarly to the problem described in #266, Host-Only interfaces could be also not connected to the host machine, so it causes an exception when Vagrant tries to parse its IP:
```
stderr: /Users/legal/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/bundler/gems/vagrant-a4f45a18a653/lib/vagrant/util/network_ip.rb:35:in `ip_parts': undefined method `split' for nil:NilClass (NoMethodError)
from /Users/legal/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/bundler/gems/vagrant-a4f45a18a653/lib/vagrant/util/network_ip.rb:19:in `network_address'
from /Users/legal/Documents/vagrant-parallels/lib/vagrant-parallels/action/network.rb:454:in `block in hostonly_find_matching_network'
from /Users/legal/Documents/vagrant-parallels/lib/vagrant-parallels/action/network.rb:449:in `each'
from …
```
=> Fix an exception when the host is not connected to host-only interface

test/unit/action/network_test.rb, test/unit/support/shared/parallels_context.rb
* Add unit tests for `action/network`
* Constrain `ruby_dep` gem versions to prevent constraints on ruby versions (port of https://github.com/mitchellh/vagrant/pull/7684/)
=> Add unit tests for action/network

lib/vagrant-parallels/action/network.rb, lib/vagrant-parallels/driver/base.rb, lib/vagrant-parallels/driver/pd_12.rb, lib/vagrant-parallels/errors.rb, locales/en.yml, test/unit/action/network_test.rb
**NB!** This feature is supported only for Parallels Desktop 12 and higher. This is caused by the `prlctl` option `--host-assign-ip6 on` appeared in PD 12. Without this option, by the default behavior the host's interface will not be configured with IPv6 address.
This PR is a partial port of https://github.com/mitchellh/vagrant/pull/6342. Also, it includes some enhancements from https://github.com/mitchellh/vagrant/pull/7699.
=> IPv6 support for Host-Only networks (PD 12+)

vagrant-parallels.gemspec
- Remove "bundler" from dev dependencies (port of the upstream PR https://github.com/mitchellh/vagrant/pull/7793)
- Constraint "rake" version to workaround "rspec" error (port of the upstream commit https://github.com/mitchellh/vagrant/commit/b2457e3e212d9af033e57e6027802d8ef78157b3)
=> Fix TravisCI build

lib/vagrant-parallels/action/sane_defaults.rb
Fixes the following issues:
- #281
- https://github.com/chef/bento/issues/695
The details are explained in this comment: https://github.com/Parallels/vagrant-parallels/issues/281#issuecomment-264632082
TL;DR: We should disable the built-in Parallels Desktop feature of auto-updating Parallels Tools in VMs because it collides with the similar feature managed by our Vagrant provider and could cause provision failures.
If you want to keep Parallels Tools in your VMs up-to-date, please, enable an appropriate provider feature:
```ruby
config.vm.provider "parallels" do |prl|
prl.update_guest_tools = true
end
```
cc: @romankulikov
=> Disable Parallels Desktop feature "--tools-autoupdate"

lib/vagrant-parallels/driver/base.rb, lib/vagrant-parallels/guest_cap/windows/install_parallels_tools.rb, lib/vagrant-parallels/plugin.rb, website/docs/source/docs/configuration.html.md
This PR adds a possibility to update Parallels Tools in Windows guests using the common provider option:
```ruby
config.vm.provider "parallels" do |prl|
prl.update_guest_tools = true
end
```
It was working fine for Linux and Mac OS X guests for a while.
Until this moment, for Windows guests we were using the internal Parallels Desktop feature of auto-updating Parallels Tools. But now we are going to disable it globally (https://github.com/Parallels/vagrant-parallels/pull/283), so this PR provides a proper way to keep PT up-to-date in Windows guests as well.
=> Implement "install_parallels_tools" guest capability for Windows

lib/vagrant-parallels/guest_cap/linux/install_parallels_tools.rb
It's pretty odd, but argument `--info` doesn't work if the internal feature `--tools-autoupdate` is disabled (we've disabled it in GH-283)
So we should use `--install` here since it always installs/updates Parallels Tools for Linux regardless of any other conditions.
=> Fix "ptiagent" argument in "install_parallels_tools" guest cap

lib/vagrant-parallels/action/export.rb
Attempting to run 'vagrant package --output mybox.box' was failing with:
.vagrant.d/gems/2.2.5/gems/vagrant-parallels-1.7.2/lib/vagrant-parallels/action/export.rb:89:in `block in convert_to_full': uninitialized constant VagrantPlugins::Parallels::Action::Export::Nokogiri (NameError)
from /Users/steve/.vagrant.d/gems/2.2.5/gems/vagrant-parallels-1.7.2/lib/vagrant-parallels/action/export.rb:87:in `each'
from /Users/steve/.vagrant.d/gems/2.2.5/gems/vagrant-parallels-1.7.2/lib/vagrant-parallels/action/export.rb:87:in `convert_to_full'
from /Users/steve/.vagrant.d/gems/2.2.5/gems/vagrant-parallels-1.7.2/lib/vagrant-parallels/action/export.rb:21:in `call'
...
Adding in the 'require' solves the problem
=> Added "require 'nokogiri'"

lib/vagrant-parallels/action.rb, lib/vagrant-parallels/action/resume.rb
At the moment VM could not be started/stopped/deleted if it is in `:paused` state (don't mix it up with `:suspended`). `prlctl` doesn't allow that by some reason:
```
$ prlctl stop paused-vm-name
Stopping the VM...
Failed to stop the VM: Unable to complete the operation. This operation cannot be completed because the virtual machine "paused-vm-name is in the "paused" state.
$ prlctl delete paused-vm-name
Removing the VM...
Failed to remove the VM: Unable to perform the action because the virtual machine is busy. The virtual machine is currently running. Please try again later.
```
This PR fixes the related issue - the VM will be resumed before the `halt` action. Also, on the `up` action it will be just resumed to avoid further errors while redundant re-configuration.
=> Handle "paused" VM state for up and halt actions

lib/vagrant-parallels/action.rb
That is a port of the upstream Vagrant commit:
https://github.com/mitchellh/vagrant/commit/e42f346b1d5891b5bd3651564894b95ed3b8b6cc
>Previously, there was no one gesture that would start a VM if it was not
running and run the appropriate provisioners regardless of its original
state. `vagrant up` did nothing if the VM was running, while
`vagrant provision` did nothing if the VM was not running.
>Change the semantics of `vagrant up`, via the start actions of the providers,
to go through the provisioning logic even if the VM is already running.
The semantics of `run: "once"` vs `run: "always"` are respected.
=> Make `start` action run provisioners if VM is running

lib/vagrant-parallels/synced_folder.rb
That fixes invalid share names in Windows guests, where backward slash
character is used as a path separator.
_Details:_
Currently, if we define the synced folder this way (for Windows guest):
```ruby
config.vm.synced_folder "../", 'C:\Users\vagrant\my_share'
```
then the share id will be this string: `'C_\Users\vagrant\my_share'`
In the guest it will be exposed as `\\psf\C_Usersvagrantmy_share` - Parallels Desktop tries to replace backslashes with some special character by itself. Meanwhile the Vagrant expects that the 
share is available at `\\psf\C_Usersvagrantmy_share`, so it creates a broken symlink.
This Pull-Request adds `\` to the regex, so this char will be replaced with `_`.
The result share name will be `'C__Users_vagrant_my_share'` and it will be available at …
=> Escape backward slashes in synced folder id

vagrant-parallels.gemspec
This PR fixes https://github.com/Parallels/vagrant-parallels/issues/297
In Vagrant 1.9.5 there was "nokogiri" gem removed from the Vagrant bundle: https://github.com/mitchellh/vagrant/pull/8571
So now we should specify it as a dependency of `vagrant-parallels` gem if we want to use it.
**NB!** After that PR is merged & released, it will cause a crash of plugin upgrade/installation with Vagrant 1.9.5, similar to this https://github.com/mitchellh/vagrant/issues/8594
To work it around we need to define a special env variable before running the plugin installation:
```
export NOKOGIRI_USE_SYSTEM_LIBRARIES=true 
vagrant plugin install vagrant-parallels
```
Hopefully, this trick will not be needed for future versions of Vagrant (after 1.9.5), since it was fixed in the Vagrant installer: …
=> Add "nokogiri" as a runtime dependency

website/docs/source/docs/installation/index.html.md
The current installation doc links to `/downloads` on the vagrant site but the url is `/downloads.html`.
=> fix link to vagrant downloads page

lib/vagrant-parallels/action/box_register.rb
Fixes #303 
The name of box VM, as well as *.pvm dir name, will be changed by Parallels Desktop automatically if there is already any VM registered with the same name. So, we should read the actual box path before trying to access its content.
=> box_register: Read box path right before opening config.pvs

lib/vagrant-parallels/driver/base.rb
It prevents warnings in newer Ruby versions (>= 2.4.0).
Fixes #311
=> driver: Move "execute_prlctl" outside of the private scope

test/acceptance/provider/package_spec.rb
Fixes #312 
P.s. Actually, the same issue was recently fixed in the upstream (virtualbox) implementation of `package_spec.rb`: https://github.com/hashicorp/vagrant-spec/commit/7ac8b4191de578e345b29acaf62ecc72c8e73be1
=> test/acceptance: Use correct environment when starting the guest

website/docs/README.md, website/docs/source/docs/boxes/base.html.md, website/docs/source/docs/boxes/index.html.md, website/docs/source/docs/boxes/packer.html.md, website/docs/source/docs/configuration.html.md, website/docs/source/docs/getting-started.html.md, website/docs/source/docs/index.html.md, website/docs/source/docs/installation/index.html.md, website/docs/source/docs/installation/uninstallation.html.md, website/docs/source/docs/networking/forwarded_ports.html.md, website/docs/source/docs/networking/index.html.md, website/docs/source/docs/networking/private_network.html.md, website/docs/source/docs/networking/public_network.html.md, website/docs/source/docs/share.html.md, website/docs/source/docs/usage.html.md
- Mention PD 13 support
- Update links to official Vagrant docs
- Update links to Parallels official docs
- Update links to Vagrant Cloud. Former Atlas, it was renamed back to Vagrant Cloud.
- Add a link to the known issue with Vagrant 1.9.6
- Update website README.md
=> Update the documentation website

lib/vagrant-parallels/action/network.rb, lib/vagrant-parallels/errors.rb, locales/en.yml
Fixes #339 
In Vagrant v2.0.4 the exception `Vagrant::Errors::NetworkCollision` class has been modified, 2 arguments were added: https://github.com/hashicorp/vagrant/pull/9685
We port it locally here in order to keep backward compatibility with older Vagrant versions.
=> Fix error message for host-only network collision

README.md
Updated link to Vagrant downloads page to include .html - The previous link returned a 404 error.
=> Fix broken link to Vagrant downloads

CONTRIBUTING.md, vagrant-parallels.gemspec
This PR updates gem dependencies, such as `rake`, as suggested by the GitHub security alert.
Also, I updated the CONTRIBUTING.md guidelines by adding `bundle exec`, assuming that `rake` from our `Gemfile` is used.
=> Update gem dependencies

CHANGELOG.md, CONTRIBUTING.md, Gemfile, README.md, locales/en.yml, vagrant-parallels.gemspec, website/docs/README.md, website/docs/source/docs/boxes/base.html.md, website/docs/source/docs/boxes/packer.html.md, website/docs/source/docs/boxes/veewee.html.md, website/docs/source/docs/configuration.html.md, website/docs/source/docs/contacts.html.md, website/docs/source/docs/getting-started.html.md, website/docs/source/docs/index.html.md, website/docs/source/docs/installation/index.html.md, website/docs/source/docs/networking/private_network.html.md, website/docs/source/docs/networking/public_network.html.md
I noticed the latest Parallels documentation is v15 but the site has v14 links, and trying to load the non-existent v16 redirects to the current v15, so I kept v16 because I assume it will remain up-to-date for longer.
Since I'm updating links anyway, I thought I might as well change them (and test the links) to HTTPS, too. I did not update scripts because I haven't tested if they still work.
=> Changed non-script docs from HTTP to HTTPS and v14 to v16

Gemfile
Default branch name has changed to `main`
=> Update vagrant-spec branch name in Gemfile

Gemfile
Looks like vagrant has moved from mitchelh to vagrant. Updates the gemfile to reflect this.
=> chore: update gemfile dependency to point at correct repo

lib/vagrant-parallels/action.rb, lib/vagrant-parallels/action/package_vagrantfile.rb
Currently `vagrant package --vagrantfile myvagrantfile` is broken. 
It copies the custom vagrant to the box archive, however the custom vagrantfile `includes/_Vagrantfile` is never loaded by the actual vagrantfile `./vagrantfile`
This PR adds the package_vagrantfile action (stolen from the virtualbox provider). 
This means that the following template will be rendered:
https://github.com/hashicorp/vagrant/blob/6e670777aff01043b7c21e60dd2ce95b5e433806/templates/package_Vagrantfile.erb#L10
Causing the custom vagrantfile that is already copied to actually be referenced and to work.
=> fix: broken custom vagrantfile support

lib/vagrant-parallels/driver/base.rb, test/unit/action/network_test.rb, test/unit/support/shared/parallels_context.rb
Fixes https://github.com/Parallels/vagrant-parallels/issues/369
The field `Bound To` is not printed anymore in the output of `prlsrvctl net info` on macOS 11.0+, so we shouldn't rely on it.
=> Do not  expect "Bound To" field to be present in "prlsrvctl net info"

lib/vagrant-parallels/action/box_unregister.rb
Fixes https://github.com/Parallels/vagrant-parallels/issues/357
This PR fixes the concurrency issue of box un-register when running in multi-vm environment.
There was a sad mistake in this file. If we start the lease counter with 0, we should obviously expect to get back to 0 when the last VM cloning the the box is ready to release it.
=> Fix the concurrency issue with box un-register in multi-vm environment

lib/vagrant-parallels/cap/mount_options.rb, lib/vagrant-parallels/errors.rb, lib/vagrant-parallels/guest_cap/linux/mount_parallels_shared_folder.rb, lib/vagrant-parallels/plugin.rb, lib/vagrant-parallels/synced_folder.rb, lib/vagrant-parallels/util/unix_mount_helpers.rb, locales/en.yml
This PR ports the functionality "Persist Shared Folders after manual reboot" for Linux gusest, which has been recently implemented in upstream Vagrant :
- https://github.com/hashicorp/vagrant/pull/11570
- https://github.com/hashicorp/vagrant/pull/11797
Now shared folder mounts are added to `/etc/fstab` on the guest side, so the they will be properly re-mounted after a "manual" reboot of the VM.
Fixes #376
Fixes #290
=> Implement "mount_options" and "mount_type" capabilities, persisting shared folders after manual reboot

lib/vagrant-parallels/cap/mount_options.rb, lib/vagrant-parallels/synced_folder.rb
Fixes https://github.com/Parallels/vagrant-parallels/issues/384
Vagrant 2.2.15 includes hashicorp/vagrant#12184 which apparently changes the expected interface of `mount_name` synced folder capability. It seems that Vagrant maintainers didn't consider that there could be other plugins implementing this capability on their side :(
As the result, in order to keep the backward compatibility with older versions of Vagrant we have to do a dirty hack with `mount_name` implementation, assuming that it could be called with 2 or 3 positional arguments.
=> [cap/mount_options] Fix "mount_name" compatibility with Vagrant 2.2.15+

lib/vagrant-parallels/cap/mount_options.rb, lib/vagrant-parallels/synced_folder.rb
This PR fixes a critical bag introduced in `vagrant-parallels` v2.2.0 (Linux guests only): https://github.com/Parallels/vagrant-parallels/issues/389
Changes:
1. Move shared folder setup from `enable` stage to `prepare`. In this case shared folders will be setup in the VM (via `prlctl`) before the VM is booted, so the filesystem will be available in the guest OS on early stage. 
In `virtualbox` provider it is done similarly: https://github.com/hashicorp/vagrant/blob/22795b161bf67a4c0ebbe32c9ce8777cb888c4a7/plugins/providers/virtualbox/synced_folder.rb#L17-L19
2. Add `_netdev` mount option by default to all `prl_fs` filesystems. That will prevent VM from boot failure if the shared folder (filesystem) is not available. 
`virtualbox` provider does the same for vboxfs: …
=> Fix shared folder mount on the VM reboot

lib/vagrant-parallels/action/network.rb, test/unit/action/network_test.rb
Due to changes, ruby 3 handles keyword arguments, `network_args` has to be passed as `**network_args`
I also added some code cleanup. The tests now run fine again.
I am new to ruby, so bear with me, if something is not right, I will make changes accordingly.
=> Fixed tests and cleaned up code

lib/vagrant-parallels/action/forward_ports.rb
This fixes the broken port forwarding of issue #393. Due to ruby3 handling kwargs differently, they now have to be passed with leading double asterisks. 
I'd recommend merging #395 first, as the test suite is also broken because of this issue.
I am new to ruby and open to any recommendations and improvements regarding this language.
=> Fixed message_attribute to be kwargs #393

lib/vagrant-parallels/config.rb, lib/vagrant-parallels/driver/base.rb, lib/vagrant-parallels/guest_cap/darwin/install_parallels_tools.rb, lib/vagrant-parallels/guest_cap/linux/install_parallels_tools.rb, test/unit/driver/base_test.rb
Implements arm (aarch) determination support for installing the correct Parallels Tools ISO on linux & darwin guests.
Requests the arch directly from the guest using `uname` over the SSH connection. Adds basic unit tests for the updated `read_guest_tools_iso_path` function.
=> Issue 401 - m1 support

website/docs/source/docs/boxes/index.html.md, website/docs/source/docs/getting-started.html.md, website/docs/source/docs/usage.html.md
This is a hotfix in addition to https://github.com/Parallels/vagrant-parallels/pull/436
Due to the imperfections in our current static website generator (`middleman`) we have to add newlines before every code snippet block.
JFYI, @sai-kumar-peddireddy
=> [docs] Hotfix for newlines and whitespaces

Gemfile, vagrant-parallels.gemspec
- [gemspec: Add webrick dependency](https://github.com/Parallels/vagrant-parallels/commit/cfcb78c3faab8c91a36e92dd1cfca0ba53584e42) 
It is not included in Ruby 3.0 standard lib anymore, so we should add it explicitly
- [gemspec: Fix compatibility with Ruby 2.7 and older](https://github.com/Parallels/vagrant-parallels/commit/7fff7c09f3a409caae0fb6c3f9a840c6e5498723) 
Vagrant 2.3.* is still using Ruby 2.7 as the embedded ruby interpreter. We should not include a strict "required_ruby_version"
in our gemfile, otherwise it won't be possible to install our plugin on Vagrant 2.3* or older.
It's better to remove the line completely and rely on the compatibility defined by the upstream Vagrant.
- [Gemfile: Update dev dependencies](https://github.com/Parallels/vagrant-parallels/commit/9ee6da376e37b …
=> Fix compatibility with both Ruby 2.7 and Ruby 3.0

lib/vagrant-parallels/driver/base.rb
It completes the fix introduced in https://github.com/Parallels/vagrant-parallels/pull/434
The previous statement with `||` operator always returned empty string if it was returned by `read_guest_ip_dhcp`. Now we are checking the result properly.
Also, I added the loop to make sure that we wait for the real IP instead of returning `''` expecting the SSH client to retry.
=> driver: Fix the detection of VM IP using prlctl command

lib/vagrant-parallels/action/import.rb, lib/vagrant-parallels/action/prepare_clone_snapshot.rb, lib/vagrant-parallels/action/sane_defaults.rb, lib/vagrant-parallels/plugin.rb, lib/vagrant-parallels/synced_folder.rb, lib/vagrant-parallels/synced_folder_macvm.rb, lib/vagrant-parallels/util/common.rb
This is the alternative implementation of #446, which is supposed to fix the current issue of mounting synced folders on *.macvm guests: #445 
Here I moved the synced folder support for *macvm to a separate class, `SyncedFolderMacVM`. It is just a placeholder for now and should still be filled with the proper implementation for macvms, as it was discussed here: https://github.com/Parallels/vagrant-parallels/pull/446#issuecomment-1554461800
Fixes #445 
Closes #446 as superseded
=> Add a placeholder synced folder class for Mac VMs

CONTRIBUTING.md
I added a note to `CONTRIBUTING.md`, which clarifies the details of releasing a new versions of `vagrant-parallels`.
=> Add a doc note for releasing a new provider version

lib/vagrant-parallels/driver/base.rb, lib/vagrant-parallels/util/common.rb, test/unit/support/shared/pd_driver_examples.rb
Vagrant uses `prlctl clone` to make a copy of the stored box when `up`'ing a VM. On Intel, this can be a linked clone, but on ARM, this is not an option with Apple's MacVMs. As such, Parallels does a full traditional copy of the box files into a new location that is then registered resulting in the requirement of `2(box size)` space. Since MacVMs can be quite large (in our case 30-40GB after all our preparation and additional software), this can quickly run a laptop out of space with just a VM or two. (There's other factors here as well, like APFS snapshots if you're running Time Machine which will hold on to space after you've destroyed VMs.)
APFS supports the `clonefile(2)` call which creates a copy-on-write clone of the file meaning it's effectively a quick and free operation to fork a …
=> use clonefile copy for macvm boxes

lib/vagrant-parallels/driver/base.rb, lib/vagrant-parallels/util/common.rb, test/unit/support/shared/pd_driver_examples.rb
This reverts commit dbe3495cd3fbf09642cbd21f602bf8280c12d6d2.
Native copy is implemented in Parallels Desktop 19.2.1. Users can now update to latest version & use this feature.
=> Revert "use clonefile copy for macvm boxes"

lib/vagrant-parallels/driver/base.rb, lib/vagrant-parallels/guest_cap/windows/install_parallels_tools.rb, test/unit/driver/base_test.rb
Looks like at some point PTIAgent.exe was removed from the Parallels Desktop app bundle and so this plugin updating tools on Windows no longer works.
The current tools distribution for Windows is via ISOs in the app bundle now just as Linux and Mac are. We can copy the ISO and mount it with Powershell, then execute the updater.
Tested this with Parallels 19 and Windows 11 22h2 image with an outdated tools from earlier 19.x releases.
```
==> win11-22h2-arm: Booting VM...
==> win11-22h2-arm: Waiting for machine to boot. This may take a few minutes...
win11-22h2-arm: SSH address: fe80::db6b:6e69:542c:9439:22
win11-22h2-arm: SSH username: vagrant
win11-22h2-arm: SSH auth method: private key
win11-22h2-arm: Warning: Host unreachable. Retrying...
win11-22h2-arm: Warning: Connection refused. …
```
=> Support guest tools updates on Windows again (for ARM also)

lib/vagrant-parallels/guest_cap/linux/mount_parallels_shared_folder.rb
* Fixes #483 
I've been encountering the same issue outlined in #483 and other places.  This change checks for `prl_fsd` and, if found, uses it to mount the defined shares in the expected locations; otherwise it falls back to the old `mount` command, accommodating older installs as well as VMs on Parallels 20 that have not yet updated the tools to 20.2.0+.
My test matrix for this is very narrow, but it works; Parallels, and Vagrant, are essential to my own developer workflow. I've been using Parallels since version 2.0, I'm not inclined to move away from it unless I *had* to, but this issue going unresolved has threatened that.  Hopefully it helps! 
For anybody wanting to test this locally, this file should replace the one in
> ${HOME}/.vagrant.d/gems/3.3.6/gems/vagrant-parallels-2.4.2/lib …
=> Add a check for prl_fsd and use that to mount if it exists.

README.md
Updated README.md to mention that it's necessary to have the Xcode command line development tools installed to be able to build/install the provider plugin.
=> Update README.md to mention Xcode command line development tools

lib/vagrant-parallels/guest_cap/linux/mount_parallels_shared_folder.rb
This is a fix for #505 
If `share` is the only mount option the `o_options` is empty and the entire command ends up with an extra comma e.g. `prl_fsd /home/vagrant/trellis -o big_writes,,fsname=home_vagrant_trellis,subtype=prl_fsd --share --sf=home_vagrant_trellis`
This moves the other `-o` options into the array so that there are the correct commas
=> Ensure no empty array of options for `prl_fsd`
